#!/bin/bash
DIR=$(dirname "$(readlink -f "$0")")
clear
cd "$DIR"

export NAME=$(basename "$(pwd)")
export SOURCES=src

make -j$(sysctl -n hw.ncpu) all
make min
hpprgm $NAME-min.prgm

read -p "Press Enter to exit!"

# Close the Terminal window
osascript -e 'tell application "Terminal" to close window 1' & exit
