#!/bin/bash
DIR=$(dirname "$0")
clear
cd "$DIR"

source ../../notarization.sh

PACKAGEROOT=package-root
PRIMESDK=Applications/HP/PrimeSDK

# re-sign all binarys
find "$PACKAGEROOT/$PRIMESDK/bin" -type f -exec xattr -c {} \;
find "$PACKAGEROOT/$PRIMESDK/bin" -type f -exec codesign --remove-signature {} \;
find "$PACKAGEROOT/$PRIMESDK/bin" -type f -exec codesign --sign "Developer ID Application: $YOUR_NAME ($TEAM_ID)" --options runtime --timestamp {} \;

./build.sh

read -p "Press Enter to exit!"

# Close the Terminal window
osascript -e 'tell application "Terminal" to close window 1' & exit
