#!/bin/bash
DIR=$(dirname "$0")
clear
cd "$DIR"

source ../../notarization

./build.sh

read -p "Press Enter to exit!"

# Close the Terminal window
osascript -e 'tell application "Terminal" to close window 1' & exit
