#!/bin/bash
DIR=$(dirname "$0")
clear
cd "$DIR"

PRIMESDK=Applications/HP/PrimeSDK
NAME=PrimeSDK
IDENTIFIER=uk.insoft.$NAME

#hpprgm
cp -p -rf ../PrimePlus/Package\ Installer/package-root/$PRIMESDK/hpprgm/*.hpprgm package-root/$PRIMESDK/hpprgm
cp -p -rf ../PPL-Font/Package\ Installer/package-root/$PRIMESDK/hpprgm/*.hpprgm package-root/$PRIMESDK/hpprgm
cp -p -rf ../GROB/Package\ Installer/package-root/$PRIMESDK/hpprgm/*.hpprgm package-root/$PRIMESDK/hpprgm

#pplib
cp -p -rf ../PrimePlus/Package\ Installer/package-root/$PRIMESDK/pplib/*.pplib package-root/$PRIMESDK/pplib


find . -name '*.DS_Store' -type f -delete

read -p "Press Enter to exit!"

# Close the Terminal window
osascript -e 'tell application "Terminal" to close window 1' & exit
