#!/bin/bash
DIR=$(dirname "$0")
clear
cd $DIR

PACKAGEROOT=package-root
PRIMESDK=Applications/HP/PrimeSDK
NAME=PrimeSDK
IDENTIFIER=uk.insoft.$NAME

IDENTITY=security find-identity -v -p basic | awk -F'"' '/Developer ID Installer:/ {print $2}'
APPLE_ID="richie_uk@icloud.com"
TEAM_ID="8XN79M4JCJ"
PASSWORD="bljo-uqdx-niju-qmwp"

cp -p -rf ../../piXfont/installer/$PACKAGEROOT/$PRIMESDK/hpprgm/*.hpprgm $PACKAGEROOT/$PRIMESDK/hpprgm
cp -p -rf ../../piXfont/build/* $PACKAGEROOT/$PRIMESDK/bin

cp -p -rf ../../GROB/installer/$PACKAGEROOT/$PRIMESDK/hpprgm/*.hpprgm $PACKAGEROOT/$PRIMESDK/hpprgm
cp -p ../../GROB/installer/$PACKAGEROOT/$PRIMESDK/bin/grob $PACKAGEROOT/$PRIMESDK/bin

cp -p -rf ../../PPL_Reformat/installer/$PACKAGEROOT/$PRIMESDK/hpprgm/*.hpprgm $PACKAGEROOT/$PRIMESDK/hpprgm
cp -p ../../PPL_Reformat/installer/$PACKAGEROOT/$PRIMESDK/bin/pplref $PACKAGEROOT/$PRIMESDK/bin

cp -p -rf ../../PPL_Minifier/installer/$PACKAGEROOT/$PRIMESDK/hpprgm/*.hpprgm $PACKAGEROOT/$PRIMESDK/hpprgm
cp -p ../../PPL_Minifier/installer/$PACKAGEROOT/$PRIMESDK/bin/pplmin $PACKAGEROOT/$PRIMESDK/bin

cp -p -rf ../../PrimePlus/installer/$PACKAGEROOT/$PRIMESDK/hpprgm/*.hpprgm $PACKAGEROOT/$PRIMESDK/hpprgm
cp -p -rf ../../PrimePlus/installer/$PACKAGEROOT/$PRIMESDK/pplib/*.pplib $PACKAGEROOT/$PRIMESDK/pplib
cp -p ../../PrimePlus/installer/$PACKAGEROOT/$PRIMESDK/bin/p+ $PACKAGEROOT/$PRIMESDK/bin/p+

pkgbuild --root package-root \
         --identifier $IDENTIFIER \
         --version 1.1 --install-location / \
         --scripts scripts \
         $NAME.pkg

productsign --sign "Developer ID Installer: Richard Hughes (8XN79M4JCJ)" $NAME.pkg $NAME-signed.pkg
pkgutil --check-signature $NAME-signed.pkg

xcrun notarytool submit --apple-id $APPLE_ID \
                        --password $PASSWORD \
                        --team-id $TEAM_ID \
                        --wait $NAME-signed.pkg
                        
read -p "Press Enter to continue."

./update_distribution.sh
#productbuild --distribution distribution.xml \
#             --resources resources \
#             --package-path $NAME-signed.pkg \
#             $NAME-installer.pkg
 
productsign --sign "Developer ID Installer: Richard Hughes (8XN79M4JCJ)" $NAME-installer.pkg $NAME-installer-signed.pkg
pkgutil --check-signature $NAME-installer-signed.pkg

#xcrun notarytool submit --apple-id $APPLE_ID \
#                        --password $PASSWORD \
#                        --team-id $TEAM_ID \
#                        --wait $NAME-installer-signed.pkg
                        
read -p "Press Enter to continue."

rm -rf $NAME.pkg
rm -rf $NAME-signed.pkg
rm -rf $NAME-installer.pkg

spctl -a -v $NAME-installer-signed.pkg

read -p "Press Enter to exit!"

# Close the Terminal window
osascript -e 'tell application "Terminal" to close window 1' & exit
